[mgr]
show_hidden = true

[opener]
play = [
    {run = 'mpv "$@"', orphan = true}
]
edit = [
    {run = 'code "$@"', orphan = true}
]
img = [
    {run = 'koko "$@"', orphan = true}
]

[open]
prepend_rules = [
    {mime = "image/*", use= "img"},
]